# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ghash/Dokumenty/time-series-data-reader

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ghash/Dokumenty/time-series-data-reader

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ghash/Dokumenty/time-series-data-reader/CMakeFiles /home/ghash/Dokumenty/time-series-data-reader/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ghash/Dokumenty/time-series-data-reader/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named data

# Build rule for target.
data: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 data
.PHONY : data

# fast build rule for target.
data/fast:
	$(MAKE) -f CMakeFiles/data.dir/build.make CMakeFiles/data.dir/build
.PHONY : data/fast

#=============================================================================
# Target rules for targets named data_test

# Build rule for target.
data_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 data_test
.PHONY : data_test

# fast build rule for target.
data_test/fast:
	$(MAKE) -f CMakeFiles/data_test.dir/build.make CMakeFiles/data_test.dir/build
.PHONY : data_test/fast

src/file.o: src/file.cpp.o
.PHONY : src/file.o

# target to build an object file
src/file.cpp.o:
	$(MAKE) -f CMakeFiles/data.dir/build.make CMakeFiles/data.dir/src/file.cpp.o
	$(MAKE) -f CMakeFiles/data_test.dir/build.make CMakeFiles/data_test.dir/src/file.cpp.o
.PHONY : src/file.cpp.o

src/file.i: src/file.cpp.i
.PHONY : src/file.i

# target to preprocess a source file
src/file.cpp.i:
	$(MAKE) -f CMakeFiles/data.dir/build.make CMakeFiles/data.dir/src/file.cpp.i
	$(MAKE) -f CMakeFiles/data_test.dir/build.make CMakeFiles/data_test.dir/src/file.cpp.i
.PHONY : src/file.cpp.i

src/file.s: src/file.cpp.s
.PHONY : src/file.s

# target to generate assembly for a file
src/file.cpp.s:
	$(MAKE) -f CMakeFiles/data.dir/build.make CMakeFiles/data.dir/src/file.cpp.s
	$(MAKE) -f CMakeFiles/data_test.dir/build.make CMakeFiles/data_test.dir/src/file.cpp.s
.PHONY : src/file.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/data_test.dir/build.make CMakeFiles/data_test.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/data_test.dir/build.make CMakeFiles/data_test.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/data_test.dir/build.make CMakeFiles/data_test.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/time_series.o: src/time_series.cpp.o
.PHONY : src/time_series.o

# target to build an object file
src/time_series.cpp.o:
	$(MAKE) -f CMakeFiles/data.dir/build.make CMakeFiles/data.dir/src/time_series.cpp.o
	$(MAKE) -f CMakeFiles/data_test.dir/build.make CMakeFiles/data_test.dir/src/time_series.cpp.o
.PHONY : src/time_series.cpp.o

src/time_series.i: src/time_series.cpp.i
.PHONY : src/time_series.i

# target to preprocess a source file
src/time_series.cpp.i:
	$(MAKE) -f CMakeFiles/data.dir/build.make CMakeFiles/data.dir/src/time_series.cpp.i
	$(MAKE) -f CMakeFiles/data_test.dir/build.make CMakeFiles/data_test.dir/src/time_series.cpp.i
.PHONY : src/time_series.cpp.i

src/time_series.s: src/time_series.cpp.s
.PHONY : src/time_series.s

# target to generate assembly for a file
src/time_series.cpp.s:
	$(MAKE) -f CMakeFiles/data.dir/build.make CMakeFiles/data.dir/src/time_series.cpp.s
	$(MAKE) -f CMakeFiles/data_test.dir/build.make CMakeFiles/data_test.dir/src/time_series.cpp.s
.PHONY : src/time_series.cpp.s

test/test.o: test/test.cpp.o
.PHONY : test/test.o

# target to build an object file
test/test.cpp.o:
	$(MAKE) -f CMakeFiles/data.dir/build.make CMakeFiles/data.dir/test/test.cpp.o
	$(MAKE) -f CMakeFiles/data_test.dir/build.make CMakeFiles/data_test.dir/test/test.cpp.o
.PHONY : test/test.cpp.o

test/test.i: test/test.cpp.i
.PHONY : test/test.i

# target to preprocess a source file
test/test.cpp.i:
	$(MAKE) -f CMakeFiles/data.dir/build.make CMakeFiles/data.dir/test/test.cpp.i
	$(MAKE) -f CMakeFiles/data_test.dir/build.make CMakeFiles/data_test.dir/test/test.cpp.i
.PHONY : test/test.cpp.i

test/test.s: test/test.cpp.s
.PHONY : test/test.s

# target to generate assembly for a file
test/test.cpp.s:
	$(MAKE) -f CMakeFiles/data.dir/build.make CMakeFiles/data.dir/test/test.cpp.s
	$(MAKE) -f CMakeFiles/data_test.dir/build.make CMakeFiles/data_test.dir/test/test.cpp.s
.PHONY : test/test.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... data"
	@echo "... data_test"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... src/file.o"
	@echo "... src/file.i"
	@echo "... src/file.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/time_series.o"
	@echo "... src/time_series.i"
	@echo "... src/time_series.s"
	@echo "... test/test.o"
	@echo "... test/test.i"
	@echo "... test/test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

